"""AI Market Brief, generated by Google Gemini.

Gemini only *explains* numbers. Every value in the prompt is computed beforehand by
services/analytics.py (`brief_facts`), and the prompt tells the model not to
recalculate or add numbers.

The API key is read from the GEMINI_API_KEY environment variable on the server, at
call time, and is sent only in the X-goog-api-key header. It never appears in a URL,
a log line, or a response to the browser.
"""

import logging
import os
import time

import requests

log = logging.getLogger(__name__)

MODEL = "gemini-flash-latest"
# Used once if MODEL is overloaded: Google's flash models often answer 503 UNAVAILABLE
# at peak load, and retrying the same model right away rarely helps.
FALLBACK_MODEL = "gemini-flash-lite-latest"
GEMINI_URL = "https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent"
TIMEOUT_SECONDS = 20  # per attempt; at most two attempts stay under the page's 45s wait
CAPACITY_STATUSES = {429, 500, 503, 504}  # worth one try on the fallback model

INSTRUCTIONS = """You are generating a concise MarketLens market brief.

The numerical values provided below have already been calculated by deterministic software.
Do not recalculate them.
Do not invent additional numbers.
Do not claim to know why the market moved unless explicit contextual information is supplied.
Describe WHAT changed and what the market data indicates.
Market-implied probability reflects market pricing and is not guaranteed real-world probability.
Do not provide financial or betting advice.
Use a professional, analytical, concise tone.
Return approximately 3-5 sentences of plain text, with no headings, bullet points, or markdown."""


class BriefNotConfigured(Exception):
    """GEMINI_API_KEY is not set on the server."""


class BriefUnavailable(Exception):
    """Gemini failed or returned no usable text.

    `reason` is a short, safe code (e.g. "timeout", "http_400 INVALID_ARGUMENT") that
    contains no key or prompt content, so it can be shown in API responses and logs.
    """

    def __init__(self, reason, capacity=False):
        super().__init__(reason)
        self.reason = reason
        self.capacity = capacity  # overloaded or timed out, rather than a bad request


def is_configured():
    return bool(os.environ.get("GEMINI_API_KEY"))


def build_prompt(facts):
    """Instructions followed by the pre-computed market data, one fact per line."""
    lines = "\n".join(f"- {label}: {value}" for label, value in facts)
    return f"{INSTRUCTIONS}\n\nMarket data:\n{lines}"


def _extract_text(data):
    """Pull the generated text out of a generateContent response, or None."""
    candidates = data.get("candidates") or []
    if not candidates:
        return None
    parts = (candidates[0].get("content") or {}).get("parts") or []
    text = "".join(part.get("text", "") for part in parts if not part.get("thought"))
    return text.strip() or None


def generate_market_brief(facts):
    """Return (brief text, model used). Raises BriefNotConfigured or BriefUnavailable.

    Tries MODEL, and FALLBACK_MODEL once only if MODEL is overloaded or times out.
    """
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise BriefNotConfigured()

    prompt = build_prompt(facts)
    try:
        return _generate(MODEL, prompt, api_key), MODEL
    except BriefUnavailable as exc:
        if not exc.capacity:
            raise
        log.warning("%s unavailable (%s); trying %s", MODEL, exc.reason, FALLBACK_MODEL)
    return _generate(FALLBACK_MODEL, prompt, api_key), FALLBACK_MODEL


def _generate(model, prompt, api_key):
    """One generateContent call. Returns the text or raises BriefUnavailable."""
    started = time.monotonic()

    def elapsed():
        return f"{time.monotonic() - started:.1f}s"

    try:
        response = requests.post(
            GEMINI_URL.format(model=model),
            headers={"Content-Type": "application/json", "X-goog-api-key": api_key},
            json={"contents": [{"parts": [{"text": prompt}]}]},
            timeout=TIMEOUT_SECONDS,
        )
    except requests.Timeout:
        log.warning("%s timed out after %s", model, elapsed())
        raise BriefUnavailable(f"{model}: timeout after {elapsed()}", capacity=True) from None
    except requests.RequestException as exc:
        # Only the exception type is logged: the message could echo request details.
        log.warning("%s request failed after %s: %s", model, elapsed(), type(exc).__name__)
        raise BriefUnavailable(f"{model}: network {type(exc).__name__}", capacity=True) from None

    if not response.ok:
        try:
            error = response.json().get("error") or {}
        except ValueError:
            error = {}
        # Google's error message describes the problem (bad model, bad field, quota),
        # never the key; it's logged, but only the status codes go back to the browser.
        log.warning("%s returned HTTP %s %s after %s: %s", model, response.status_code,
                    error.get("status", ""), elapsed(), str(error.get("message", ""))[:300])
        raise BriefUnavailable(f"{model}: http_{response.status_code} {error.get('status', '')}".strip(),
                               capacity=response.status_code in CAPACITY_STATUSES)

    try:
        data = response.json()
    except ValueError:
        log.warning("%s returned invalid JSON", model)
        raise BriefUnavailable(f"{model}: invalid_json") from None

    text = _extract_text(data)
    if not text:
        reason = (data.get("promptFeedback") or {}).get("blockReason") or (
            (data.get("candidates") or [{}])[0].get("finishReason")
        )
        log.warning("%s returned no text (reason: %s)", model, reason)
        raise BriefUnavailable(f"{model}: no_text {reason}")
    log.info("%s generated a brief in %s", model, elapsed())
    return text
