"""AI Market Brief, generated by Google Gemini.

Gemini only *explains* numbers. Every value in the prompt is computed beforehand by
services/analytics.py (`brief_facts`), and the prompt tells the model not to
recalculate or add numbers.

The API key is read from the GEMINI_API_KEY environment variable on the server, at
call time, and is sent only in the X-goog-api-key header. It never appears in a URL,
a log line, or a response to the browser.
"""

import logging
import os

import requests

log = logging.getLogger(__name__)

MODEL = "gemini-flash-latest"
GEMINI_URL = f"https://generativelanguage.googleapis.com/v1beta/models/{MODEL}:generateContent"
TIMEOUT_SECONDS = 30  # one attempt only; a failed brief can be retried from the page

INSTRUCTIONS = """You are generating a concise MarketLens market brief.

The numerical values provided below have already been calculated by deterministic software.
Do not recalculate them.
Do not invent additional numbers.
Do not claim to know why the market moved unless explicit contextual information is supplied.
Describe WHAT changed and what the market data indicates.
Market-implied probability reflects market pricing and is not guaranteed real-world probability.
Do not provide financial or betting advice.
Use a professional, analytical, concise tone.
Return approximately 3-5 sentences of plain text, with no headings, bullet points, or markdown."""


class BriefNotConfigured(Exception):
    """GEMINI_API_KEY is not set on the server."""


class BriefUnavailable(Exception):
    """Gemini failed or returned no usable text."""


def is_configured():
    return bool(os.environ.get("GEMINI_API_KEY"))


def build_prompt(facts):
    """Instructions followed by the pre-computed market data, one fact per line."""
    lines = "\n".join(f"- {label}: {value}" for label, value in facts)
    return f"{INSTRUCTIONS}\n\nMarket data:\n{lines}"


def _extract_text(data):
    """Pull the generated text out of a generateContent response, or None."""
    candidates = data.get("candidates") or []
    if not candidates:
        return None
    parts = (candidates[0].get("content") or {}).get("parts") or []
    text = "".join(part.get("text", "") for part in parts if not part.get("thought"))
    return text.strip() or None


def generate_market_brief(facts):
    """Return the brief text. Raises BriefNotConfigured or BriefUnavailable."""
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise BriefNotConfigured()

    try:
        response = requests.post(
            GEMINI_URL,
            headers={"Content-Type": "application/json", "X-goog-api-key": api_key},
            json={"contents": [{"parts": [{"text": build_prompt(facts)}]}]},
            timeout=TIMEOUT_SECONDS,
        )
    except requests.RequestException as exc:
        # Only the exception type is logged: the message could echo request details.
        log.warning("Gemini request failed: %s", type(exc).__name__)
        raise BriefUnavailable() from None

    if not response.ok:
        log.warning("Gemini returned HTTP %s", response.status_code)
        raise BriefUnavailable()

    try:
        data = response.json()
    except ValueError:
        log.warning("Gemini returned invalid JSON")
        raise BriefUnavailable() from None

    text = _extract_text(data)
    if not text:
        reason = (data.get("promptFeedback") or {}).get("blockReason") or (
            (data.get("candidates") or [{}])[0].get("finishReason")
        )
        log.warning("Gemini returned no text (reason: %s)", reason)
        raise BriefUnavailable()
    return text
